version: '3'

services:
    postgresdb:
      image: postgres
      restart: always
      ports: 
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: supersecret
        POSTGRES_USER: superuser
        POSTGRES_DB: appData

    dotnetbackend:
      build: .
      image: dotnetbackend:latest
      depends_on: 
        - postgresdb
      restart: always #workaround until there is a better way to wait for postgres

    reverseproxy:
      image: nginx
      volumes: 
        - ./Resources/ServerConfig:/etc/nginx/conf.d/
      ports:
        - 80:80
      depends_on: 
        - dotnetbackend