version: '3'

services:
    db:
      image: postgres
      restart: always
      ports: 
        - 3306:3306
      environment:
        POSTGRES_PASSWORD: supersecret
        POSTGRES_USER: application

    dotnet:
      build: .
      depends_on: 
        - db

    reverseproxy:
      image: nginx
      depends_on: 
        - dotnet
      volumes: 
        - ./Resources/ServerConfig:/etc/nginx/conf.d/
      ports:
        - 7654:80
    

