version: '3'

services:
    postgresdb:
      image: postgres
      restart: always
      ports: 
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: supersecret
        POSTGRES_USER: superuser
        POSTGRES_DB: appData

    dotnetbackend:
      build: .
      ports: 
        - 5000:80
      depends_on: 
        - postgresdb
      restart: always #workaround until there is a better way to wait for postgres

    # reverseproxy:
    #   image: nginx
    #   depends_on: 
    #     - dotnetbackend
    #   volumes: 
    #     - ./Resources/ServerConfig:/etc/nginx/conf.d/
    #   ports:
    #     - 7654:80